# Generated by Django 4.1 on 2022-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=20)),
                ("service", models.CharField(max_length=40)),
                ("massege", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=40)),
            ],
        ),
    ]
